### ISSUE TITLE
`fish_logo --help` crashed my computer

### ISSUE THREAD

**Issue by sentriz** [laughedelic/fish_logo#2]
but `fish_logo anythingelse` works as expected

**Comment by laughedelic** [comment]
@sentriz well done! 🥇 You found a way to break this super simple function 😂

It gets stuck because `--help` is passed to `set_color`:

https://github.com/laughedelic/fish_logo/blob/2284351053be5fdd6d014c5a5e65719b1ad94ab1/functions/fish_logo.fish#L13

Thanks for the report, I will add a handler for the `--help` flag.

**Comment by sentriz** [comment]
😎😎😎

**Comment by d0x2f** [comment]
Happened to me as well.

**Comment by laughedelic** [comment]
Sorry everyone that it took me so long to get back to this, but now it should be fixed, thanks to the PR from @amiller27
